---
title: "Paul Kogan-HW1"
author: "Paul Kogan"
date: "2021/9/16"
output: pdf_document
---
```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ISwR, random)
options(warn = -1)
```
**1**
```{r}
height <- c(1.55, 1.92, 1.60, 1.75, 1.58, 1.67,
            1.63, 1.82, 1.76, 1.77, 1.72, 1.85)
cat("# For best results, set tab to 4 spaces #\n\nQ1:\t1)\t",
    mean(height), "\n\t2)\t", sd(height), "\n\t3)\t", length(height),
    "\n\t4)\t", sum(height < 1.65), "\n\t5)\t ")
data.frame(height, c(height > 1.6 & height < 1.75))
```
**2**
```{r}
tmp <- matrix(rnorm(12), 3, 4)
cat("Q2:\t1)\t", sum(rowSums(tmp)[-1]), "\n\t2)\t",
    prod(colSums(tmp)[c(2, 4)]), "\n\t3)\t", dim(tmp), "\n\t4)\t",
    c((less <- tmp[2, ])[less < 0.2]), "\n\n")
```
**3**
```{r}
library(ISwR)
cat("Q3:\t1)\t\t")
subset(thuesen, blood.glucose > 10 & short.velocity > 1.5)
```
**4**
```{r}
library(random)
cat("Q4:\t1)\t", randomNumbers(15, 0, 81),
    "\n\n")
```
**5**
```{r}
prb <- c(0.2, 0.3, 0.5)
len <- length(prb)
rnd <- randomNumbers(1, len, 10^2, 1)
amt <- as.integer(rnd / len)
cat("Q5:\t1)\t", sample(sample(rnd, len), amt, TRUE, prb), "\n\t2)\t",
    rmultinom(amt, rnd, prb))
```